### ISSUE TITLE
Shard Iterator Type Can be Taken as an input

### ISSUE THREAD

**Issue by mthipparthi** [ticketea/pynesis#12]
Current Behaviour - We cant pass on shard iterator type as input.As type is defaulted to TRIM_HORIZON, hence we are not able to tail the kinesis for latest entries.
Expected behaviour :  I would like to have ShardIteratorType='LATEST' in order to tail the kinesis.In the current code, it is always defaulted to TRIM_HORIZON. It would be great if this is taken as input.

**Comment by msurdi** [comment]
Feature merged in. Thanks.

**Comment by mthipparthi** [comment]
Thanks for accepting PR.
